export const neighborhoods: { [key: string]: string[] } = {
  Prishtina: [
    "Ulpiana",
    "Dardania",
    "Bregu i Diellit",
    "Lakrishtë",
    "Arbëria",
    "Mati 1",
    "Mati 2",
    "Veternik",
    "Velania",
    "Qafa",
    "Qendra",
    "Kalabria",
    "Emshir",
    "Taslixhe",
    "Tophane",
    "Kodra e Trimave",
  ],
  Mitrovica: [
    "North Mitrovica",
    "South Mitrovica",
    "Bosniak Mahala",
    "Roma Mahalla",
    "Fidanishte",
    "Ilirida",
    "Zhabar i Poshtëm",
    "Mikronaselje (Lagjja e Minatorëve)",
    "Tri Solitera",
    "Dolina Doktoreve",
    "Brdjani (Kroi i Vitakut)",
    "Suvi Do (Suhodoll)",
  ],
  Peja: [
    "City Center (Bazaar/Çarshia)",
    "Babanaj",
    "Fidanishte",
    "Dardania",
    "Qyshk",
    "Rugova region (surrounding mountain communities)",
  ],
  Gjakova: [
    "City Center",
    "Bajram Curri",
    "Dardania",
    "Bajgora",
    "Gjakovë e Re",
    "Krasniqi",
    "Përlepnicë",
    "Blloku i Ri",
  ],
  Ferizaj: [
    "City Center",
    "Pika 6 / Zona akova",
    "Old Bazaar (Çarshia e Madhe / Hadumitku Mahala)",
    "Çabrati",
    "Ura e Gurit",
    "City Center",
    "...plus many rural settlements (e.g. Agaj, Botusha, Doli…) ",
  ],
  Gjilan: [
    "City Center / Old Bazaar",
    "Parku i Qytetit area",
    "Germia Park area",
    "...plus villages around Lake Badovc",
  ],
  Vushtrri: [
    "City Center (ancient fortress area)",
    "Rashan",
    "Roger",
    // (Note: larger town with surrounding villages)
  ],
  Shtime: ["City Center", "Strimberk", "Runik"],
  Obiliq: ["City Center", "Gërmadhë", "Llukar"],
  Lipjan: ["City Center", "Uçë", "Gllarevë"],
  "Fushë Kosovë": ["City Center", "Skivjan", "Bubël"],
  Drenas: ["City Center", "Komoran", "Likoc"],
  Kaçanik: ["City Center", "Besiane", "Proklate"],
  Dragash: ["City Center", "Brods"],
  Klinë: ["City Center", "Pekl", "Lukare"],
  Deçan: ["City Center", "Isniq", "Rashan"],
  Istog: ["City Center", "Lumbardh", "Stubëll"],
  Rahovec: ["City Center", "Malisheve", "Ormoc"],
  Suhareke: ["City Center", "Lower Suharekë", "Upper Suharekë"],
};
